apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      name: deploy-pod
      labels:
        app: deploy-app
    spec:
      containers:
      - image: ksbhatti/helloworld
        name: container1
        imagePullPolicy: IfNotPresent
