kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
  - name: pvol01
    persistentVolumeClaim:
      claimName: pvc01
  containers:
  - image: ksbhatti/logfile_nodejs
    name: container1
    volumeMounts:
    - name: pvol01
      mountPath: /data
