kind: ReplicaSet
apiVersion: apps/v1

metadata:
  name: myreplicaset

spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - prod1
  template:
    metadata:
      labels:
        app: prod1
    spec:
      containers:
      - name: replicasetcontainer
        image: ksbhatti/helloworld
        ports:
        - containerPort: 80

