kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-env
  labels:
    app: secretexample
spec:
  containers:
  - name: configmap-container
    image: ksbhatti/pkflag
    envFrom:
    - secretRef:
        name: sec01
