apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    name: db
spec:
  containers:
  - name: mysql
    image: "mysql"
    env:
      - name: MYSQL_USER
        value: test
      - name: MYSQL_PASSWORD
        value: test
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DB
        value: BucketList
    ports:
    - containerPort: 3306
